name: CRs Workflows

on:
  pull_request:
    branches:
      - "**" # This will match pull requests targeting any branch

permissions:
  # Not all workflows demonstrated here require the same permissions. Some do
  # not need the write permissions. However, GHA do not support specifying
  # permissions settings at the granularity of the step, so you need to set the
  # permissions to the union of all permissions required by all steps. Make sure
  # in your workflows to set the permissions to the minimum strictly required by
  # the workflows you use. Here we add more permissions in each PR depending on
  # the requirements.
  contents: read
  pull-requests: read

jobs:
  crs-workflows:
    # The CRs Workflows only need to be run once so we choose ubuntu-latest.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # All CRs workflows require the 'crs' tool, so you are going to need this
      # no matter which workflow you use.

      - name: Install crs
        uses: mbarbin/crs-actions/setup-crs@v1.0.0-alpha.8
        with:
          crs-version: 0.0.20250813

      # If you choose a workflow that requires `reviewdog`, you'll need to set
      # it up too. The distribution includes an shared action for this:
      #
      - name: Install reviewdog
        uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0
        with:
          reviewdog_version: v0.20.3

      # Comment on CRs in PR
      # requires: crs, reviewdog
      #
      # - name: Comment on CRs in PR
      #   uses: mbarbin/crs-actions/comment-crs-in-pr@v1.0.0-alpha.8
      #   with:
      #     crs-config: .github/crs-config.json

      # Annotate CRs in PR
      # requires: crs
      #
      # - name: Annotate CRs in PR
      #   uses: mbarbin/crs-actions/annotate-crs-in-pr@v1.0.0-alpha.8
      #   with:
      #     crs-config: .github/crs-config.json

      # Create CRs PR Check
      # requires: crs, reviewdog
      #
      - name: Create CRs PR Check
        uses: mbarbin/crs-actions/create-crs-pr-check@v1.0.0-alpha.8
        with:
          crs-config: .github/crs-config.json

      # Create CRs PR Job Summary
      # requires: crs
      #
      # - name: Create CRs PR Job Summary
      #   uses: mbarbin/crs-actions/create-crs-pr-job-summary@v1.0.0-alpha.8
      #   with:
      #     crs-config: .github/crs-config.json

      # Summarize CRs in PR
      # requires: crs
      #
      # - name: Summarize CRs in PR
      #   uses: mbarbin/crs-actions/summarize-crs-in-pr@v1.0.0-alpha.8
      #   with:
      #     crs-config: .github/crs-config.json

      # etc.
      #
